version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  queue:
    image: 'php:apache'
    restart: unless-stopped
    volumes:
      - /root/db/:/var/www/q/
      - ./auth/:/var/www/html/
